<header class="ontoy-topbar">
    <div class="ontoy-topbar-section">
        <a href="/" class="ontoy-logo">TOY</a>
    </div>
    <div class="ontoy-topbar-section">
        <!-- Favorites Menu Integration Point -->
        <div class="favmnu-wrapper" id="favMenuContainer" style="display: inline-block;">
            <button type="button" class="favmnu-trigger" id="favMenuTrigger" title="Menú de Favoritos" aria-label="Favoritos">
                <i class="fa-duotone fa-solid fa-thumbtack fa-rotate-by" style="--fa-secondary-color: #ff0000; --fa-secondary-opacity: 1; --fa-rotate-angle: 22deg;"></i>
            </button>
            <dialog class="favmnu-dropdown" id="favMenuDialog">
                <!-- div class="favmnu-section-title">Mis Favoritos</div -->
                <div class="mainmnu-header">
                    <span>Mis Favoritos</span>
                    <button type="button" class="mainmnu-close" id="favMenuClose">&times;</button>
                </div>
                <ol class="favmnu-list" id="favmnu-user-list"></ol>
                <ol class="favmnu-list favmnu-system-links" id="favmnu-sys-list"></ol>
                <div class="favmnu-actions">
                    <button type="button" class="favmnu-btn-act" id="favmnu-add-btn">
                        <i class="fa-solid fa-plus"></i> Agregar Página Actual
                    </button>
                    <button type="button" class="favmnu-btn-act" id="favmnu-manage-btn">
                        <i class="fa-solid fa-gear"></i> Organizar Favoritos
                    </button>
                </div>
            </dialog>
        </div>

        <!-- Main Hierarchical Menu Integration Point -->
        <div class="mainmnu-wrapper" id="mainMenuContainer" style="display: inline-block;">
            <button type="button" class="mainmnu-trigger" id="mainMenuTrigger" title="Menú Principal" aria-label="Menú Principal">
                <i class="fa-solid fa-bars"></i>
            </button>
            <dialog class="mainmnu-dropdown" id="mainMenuDialog">
                <div class="mainmnu-header">
                    <span>Menú Principal</span>
                    <button type="button" class="mainmnu-close" id="mainMenuClose">&times;</button>
                </div>
                <div class="mainmnu-content">
                    <ul class="mainmnu-list" id="mainmnu-list">
                        <!-- Generated by JS -->
                    </ul>
                </div>
            </dialog>
        </div>

        <button type="button" class="ontoy-topbar-icon ontoy-topbar-exit" id="btn-logout" title="Salir">
            <i class="fa-solid fa-right-from-bracket"></i>
        </button>
    </div>
</header>
